#=============================================================
# 基于x11-base，增加jdk8                                     #
#=============================================================
FROM xmc/x11-base:0.1
MAINTAINER xmc <xmc0824@163.com>


#============================================
#  安装ORACLE-JDK8,设置环境变量
#============================================
ARG VERSION=8
ARG UPDATE=191
ARG BUILD=12
ARG RANDOM=2787e4a523244c269598db4e85c51e0c
ENV JAVA_HOME /usr/lib/jvm/java-${VERSION}-oracle
ENV JRE_HOME ${JAVA_HOME}/jre

# RUN wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" \
#       -P /tmp \
#       https://download.oracle.com/otn-pub/java/jdk/"${VERSION}"u"${UPDATE}"-b"${BUILD}"/"${RANDOM}"/jdk-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz \
# 这是下载到本地目录下的处理方式，如果在线下载，需要调整一下使用以上的方式
COPY ./jdk-8u191-linux-x64.tar.gz /tmp
RUN cd /tmp && tar -zxvf jdk-"${VERSION}"u"${UPDATE}"-linux-x64.tar.gz \
    && mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${VERSION}.0_${UPDATE} "${JAVA_HOME}" \
    && rm -rf /tmp/* \
    && update-alternatives --install "/usr/bin/java" "java" "${JRE_HOME}/bin/java" 1 \
    && update-alternatives --install "/usr/bin/javac" "javac" "${JAVA_HOME}/bin/javac" 1 \
    && update-alternatives --set java "${JRE_HOME}/bin/java" \
    && update-alternatives --set javac "${JAVA_HOME}/bin/javac"
